# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e75d8241e2bb85eb17b0898540d02159051f53eaeacf5570066aad3a44fdf30e8072605f7e9f3aad40030309d4055b6e5c08a9aadfeffa9ad88e2f9e3222c74

test:
  secret_key_base: f2affb3454a75ac4917966487706801dc0664198c83ba24614148027df3166536fa5718b52dbe9beb519b33b4fb05f3114c2af9c4487508361df018c18756e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
